### ISSUE TITLE
Bias value not accounted for in the nnd3hamc example

### ISSUE THREAD

**Issue by AVSaiPavan2000** [mathworks/examples-for-building-classic-neural-networks#1]
The value of bias (b1 = [3; 3]) is not accounted for in the calculation of activation a1 in the Hamming Classification example (nnd3hamc) of Chapter 3.

**Comment by conordaly0** [comment]
I've updated the code inside `nnd3hamc` to use the correct calculation -- see [9f34092](https://github.com/mathworks/examples-for-building-classic-neural-networks/commit/9f3409281298dab1aaa1b8be5c8a50316e6a0d61)
